//  export const initialData = 
//    [
//       {
//           "page": 1,
//           "data": {
//               "Sales Executive Name": "Abhishek Anand",
//               "Sales Executive Code": "43242",
//               "File No.": ".0824K",
//               "D.O.": "24-11-23",
//               "Due Date": "20.12.24",
//               "Cust. Sign.": "Neil",
//               "Cost of Vehicle": "12 lakh",
//               "Margin Money": "1.5 lakh",
//               "Financed Amount (a-b)": "11.3 lakh",
//               "E.M.I. Amount": "135.0.0",
//               "Advance EMI": "5 lakh",
//               "F.C.": "hello I am here",
//               "Loan to vehicle Rs.": "10 lakh",
//               "Payment to Dealer": "by loan",
//               "GST": "158.2.9950",
//               "Adv. Int.": "12%",
//               "Date": "28-11-24",
//               "Ch. No./NEFT": "13524",
//               "Bank": "ICICI",
//               "Dealer Code": "59A",
//               "Dealer's Name": "Ankita Chauhan",
//               "Payment Receiver Name": "Hidikah kumar",
//               "Payment Receiver Code": "259",
//               "Vehicle Particulars": "engine, clutch",
//               "Vehicle Colour": "black",
//               "Engine No.": "590.P",
//               "Chasis No.": "240.ZP",
//               "Registration No.": "123.949",
//               "Name of the Borrower": "Naman Singh",
//               "Father's Name": "Rajat Chauhan",
//               "Adhaar No.": "59.89.56.00.96.56",
//               "Address": "Pahari II 1495 New Delhi",
//               "Phone No.": "956.436.1290",
//               "Mobile": "12245.656.8",
//               "Alt M. No.": "112",
//               "PAN No.": "124.K.P.56.K",
//               "Cheque Received": "Yes",
//               "Cheque Balance": "Zeror",
//               "Signature of Borrower": "Ankit",
//               "Signature of Guarantor": "Shalini",
//               "Regd. Office": "70/A-32, Rama Road Industrial Area, Najafgarh Road, New Delhi - 110015 Phone : 011-45000800",
//               "Corporate Office": "Plot No. 56/6, Block C, Sector-62,Gautam Buddha Nagar, Noida, Uttar Pradesh-201309",
//               "Branch Office": "Noida - 125"
//           }
//       },
//       {
//           "page": 2,
//           "data": {
//               "Sales Executive Name": "Abhinick Gupta",
//               "Sales Executive Code": "28",
//               "A.S.M / D.S.A": "ASM",
//               "File No.": "028",
//               "Due Date": "28.02.2023",
//               "Cust. Sign": "✓",
//               "Payment": {
//                   "Cost of Vehicle": "261000",
//                   "Margin Money": "61000",
//                   "Financed Amount (a-b)": "000",
//                   "E.M.I. Amount": "8000",
//                   "Advance EMI": "340",
//                   "F.C.": "140",
//                   "Loan to vehicle Rs.": "152000",
//                   "Payment to Dealer": "10000",
//                   "GST": "GST.IN.O516.8",
//                   "Adv. Int.": "0"
//               },
//               "Date": "14.05.13",
//               "Ch. No./NEFT": "158.78",
//               "Bank": "SBI",
//               "Dealer's Name": "Yadwarlal Veerana",
//               "Dealer Code": "514",
//               "Payment Receiver Name": "Abhinick Gupta",
//               "Payment Receiver Code": "068",
//               "Vehicle Particulars": {
//                   "Vehicle Colour": "Black",
//                   "Engine No.": "C1.5.8.224",
//                   "Chasis No.": "L1.5.6.7.9.4.58",
//                   "Registration No.": "29.6.6.5.0",
//                   "Name of the Borrower": "Aditi Ranjan",
//                   "Father's Name": "Kapil D.E.W. Sharma",
//                   "Adhaar No": "238.7.43.1688",
//                   "Address": "C.131, Sector 44, Noida",
//                   "Phone No.": {
//                       "Res": "926.55.6723",
//                       "Off": "1014.6689",
//                       "Mobile": "985.727.7278",
//                       "Alt No.": "844.978.2206"
//                   }
//               },
//               "PAN No.": "XXXX",
//               "Cheque Received": "10500",
//               "Cheque Balance": "156000"
//           }
//       },
//       {
//           "page": 3,
//           "data": {
//               "Sales Executive Name": "Mr. Abhishek Sharma",
//               "Sales Executive Code": "093",
//               "A.S.M./D.S.A": "DSA",
//               "Cost of Vehicle": "900000",
//               "Margin Money": "20000",
//               "Financed Amount (a-b)": "700000",
//               "E.M.I. Amount": "1583",
//               "Advance EMI": "200000",
//               "F.C.": "4500",
//               "Loan to vehicle Rs.": "780000",
//               "Payment to Dealer": "20000",
//               "GST": "28.76",
//               "Date": "12/12/24",
//               "Ch. No./NEFT": "07625",
//               "Bank": "Swiss Bank",
//               "Dealer's Name": "Ms. Anjali Prakash",
//               "Dealer Code": "0237",
//               "Payment Receiver Name": "Ms. Anish Sharma",
//               "Payment Receiver Code": "RE.007",
//               "Vehicle Colour": "White",
//               "Engine No.": "AE12Z 3745",
//               "Chasis No.": "MEZAAC38265",
//               "Registration No.": "DL02AS8001",
//               "Name of the Borrower": "Rohan Choudhary",
//               "Father's Name": "Hithik Jeoose",
//               "Aadhaar No.": "8762915 2200",
//               "Address": "37, Cadi Lane, New Delhi, 11003",
//               "Phone No.": "Res. 224466.88, Off. 294625.58",
//               "Mobile": "8999999999",
//               "Alt M.No.": "90102023040",
//               "PAN No.": "AXZ586615Z",
//               "Cheque Received": "45",
//               "Cheque Balance": "Noida",
//               "Regd. Office": "70/A-32, Rama Road Industrial Area, Najafgarh Road, New Delhi -110015 Phone: 011-45000800",
//               "Corporate Office": "Plot No. 56/6, Block C, Sector-62, Gautam Buddha Nagar, Noida, Uttar Pradesh-201309",
//               "Branch Office": "Noida"
//           }
//       },
//       {
//           "page": 4,
//           "data": {
//               "Sales Executive Name": "Naman Singhal",
//               "Sales Executive Code": "E.002",
//               "File No": "6492",
//               "Due Date": "12/12/2024",
//               "Cust. Sign": "✓",
//               "Cost of Vehicle": "₹ 92,000",
//               "Margin Money": "₹ 50,000",
//               "Financed Amount (a-b)": "₹ 92,000",
//               "E.M.I. Amount": "₹ 4,500",
//               "Advance EMI": "₹ 20,000",
//               "F.C.": "₹ 99,999",
//               "Loan to vehicle Rs": "₹ 20,000",
//               "Payment to Dealer": "₹ 10,000",
//               "Date": "12/12/2024",
//               "Ch. No./NEFT": "ABCD.1234",
//               "Bank": "SBI",
//               "Dealer Code": "DL.2001",
//               "Payment Receiver Name": "Tushar Tyagi",
//               "Payment Receiver Code": "DL.2001",
//               "Vehicle Particulars": "Activa 6G",
//               "Vehicle Colour": "Grey",
//               "Engine No": "ABCD0123",
//               "Chasis No": "ABCD42678",
//               "Registration No": "DL.12.5C.6495",
//               "Name of the Borrower": "Bid",
//               "Father's Name": "B.D.",
//               "Adhaar No": "11.2.23.449",
//               "Address": "X.47. Colony, Naida",
//               "Phone No": "741.50.5996",
//               "PAN No": "B.D.O.T.S.5569M",
//               "Cheque Received": "Yes",
//               "Cheque Balance": "",
//               "Regd. Office": "70/A-32, Rama Road Industrial Area, Najafgarh Road, New Delhi - 110015 Phone : 011-45008000",
//               "Corporate Office": "Plot No. 56/6, Block C, Sector-62, Gautam Buddha Nagar, Noida, Uttar Pradesh-201309",
//               "Branch Office": "Naida"
//           }
//       },
//       {
//           "page": 5,
//           "data": {
//               "Sales Executive Name": "Pitesh Sharma",
//               "Sales Executive Code": "RS1005",
//               "ASM/DSA": "ASM",
//               "Cost of Vehicle": "510000",
//               "Margin Money": "51000",
//               "Financed Amount (a-b)": "101000",
//               "E.M.I. Amount": "41500",
//               "Advance EMI": "10000",
//               "F.C.": "82510",
//               "Loan to vehicle Rs.": "3000000",
//               "Payment to Dealer": "101000",
//               "GST": "18",
//               "Adv. Int.": "28000",
//               "Date": "5-12-2024",
//               "Ch. No/NEFT": "NEFT11225",
//               "Bank": "IDFC",
//               "Dealer's Name": "Hathu Chauthan",
//               "Dealer Code": "00851",
//               "Payment Receiver Name": "Priyanka Varma",
//               "Payment Receiver Code": "PV8510",
//               "Vehicle Colour": "Black",
//               "Engine No.": "E1018124",
//               "Chasis No.": "CH180225",
//               "Registration No.": "R90251",
//               "Name of the Borrower": "Preeti Singh",
//               "Father's Name": "x42 Singh",
//               "Adhaar No.": "8999 2933 1800",
//               "Address": "Noida",
//               "Phone No.": "",
//               "PAN No.": "PTVJ05606L",
//               "Cheque Received": "D.D.C.",
//               "Cheque Balance": "81000",
//               "Regd. Office": "70/A-32, Rama Road Industrial Area, Najafgarh Road, New Delhi - 110015 Phone : 011-45008000",
//               "Corporate Office": "Plot No. 56/6, Block C, Sector-62,Gautam Buddha Nagar, Noida, Uttar Pradesh-201309",
//               "Branch Office": "Noida"
//           }
//       }
//   ]
  export const initialData = 
  {
    "extracted_data": [
        {
            "page": 1,
            "url": "https://transcribedblobstorage.blob.core.windows.net/ai-rep-platform/Ramender-1-3_page_1.jpg",
            "data": {
                "SR. No.": "42632",
                "D.O.": "20-11-25",
                "Sales Executive Name": "Ramender",
                "Sales Executive Code": "E729",
                "A.S.M / D.S.A": "",
                "File No": "P125",
                "Due Date": "10.01.25",
                "Cust Sign": "✔",
                "Cost of Vehicle": "14,99,000",
                "Margin Money": "20,000",
                "Financed Amount (a-b)": "10,00,000",
                "R.O.I.": "",
                "E.M.I. Amount": "30,000",
                "Period": "5 yrs",
                "Advance EMI": "60,000",
                "F.C": "",
                "Loan to vehicle Rs": "10,00,000",
                "Payment to Dealer": "5,00,000",
                "GST": "28%",
                "Adv Int": "",
                "Date": "20-12-24",
                "Ch. No/NEFT": "",
                "Bank": "",
                "Dealer's Name": "KONCEPT Automobiles",
                "Dealer Code": "C7243",
                "Payment Receiver Name": "Santosh Kumar",
                "Payment Receiver Code": "E729",
                "Vehicle Colour": "Black",
                "Engine No": "P5499. E729",
                "Chasis No": "CZ259270792",
                "Registration No": "",
                "Name of the Borrower": "ANIL KUMAR",
                "Father's Name": "AJIT KUMAR",
                "Adhaar No": "55629 972 642",
                "Address": "H. No-5 Jand Flat Mohan Garden, New Delhi-53",
                "Phone No": "8729674889",
                "PAN No": "BZXP878869",
                "Cheque Received": "",
                "Cheque Balance": ""
            }
        },
        {
            "page": 2,
            "url": "https://transcribedblobstorage.blob.core.windows.net/ai-rep-platform/Ramender-1-3_page_2.jpg",
            "data": {
                "Area Manager": "Adarsh Kumar",
                "Sales Executive": "Ravinder",
                "Dealer": "Koncept Automobiles",
                "Date Entry": "2008",
                "Date Exit": "",
                "Hirer Self Attested ID Proof": "OK",
                "Hirer Photo With Cross Sign": "OK",
                "Co-Borrower Self Attested ID Proof": "OK",
                "Co-Borrower Photo With Cross Sign": "OK",
                "Guarantor 1 Self Attested ID Proof": "OK",
                "Guarantor 1 Photo With Cross Sign": "OK",
                "Guarantor 2 Self Attested ID Proof": "OK",
                "Guarantor 2 Photo With Cross Sign": "OK",
                "Self Attested Residence Proof": "OK",
                "Own House Proof": "NO",
                "Proper & Complete Sign in File": "NO",
                "Account No": "OK",
                "Bank Name": "OK",
                "Branch": "OK",
                "Cheque Stamp": "OK",
                "Account Pay on Cheque": "OK",
                "Cheque Number": "OK",
                "FI Sheet": "OK",
                "Banking (Updated Upto Last 30 Days/Mini Statement)": "OK",
                "Salary A/C (If Applicable)": "OK",
                "Salary Slip (If Applicable)": "OK",
                "ITR (If Applicable)": "OK",
                "Cheques": "OK",
                "ACH": "NO",
                "Loan Amount Match With DO Department": "OK",
                "Guarantor Change But Not Login in DO Department": "OK",
                "Margin Money Receipt": "NO",
                "Insurance Copy": "NO",
                "Bill": "OK",
                "RTO Tax Receipt": "OK",
                "1 Key": "OK",
                "File Check by Area Manager With Stamp & Signature": "Adarsh Kumar",
                "File Verified By": "Ravinder",
                "Managing Director Sign": ""
            }
        },
        {
            "page": 3,
            "url": "https://transcribedblobstorage.blob.core.windows.net/ai-rep-platform/Ramender-1-3_page_3.jpg",
            "data": {
                "Proposal No": "",
                "Date": "20-12-24",
                "Sales Executive": "Raminder",
                "Dealership": "Koncept Automobiles",
                "Full Name of the Applicant": "Anil Kumar",
                "Date of Birth": "20.05.86",
                "Father's Name": "Ajit Kumar",
                "Residence Address": "H.No-6, Janata Flats, Sec-31, Noida 201301",
                "Tel. No. (Res.)": "8922676789",
                "Office": "",
                "Mobile": "8619722433",
                "Family Mobile Number": "",
                "Name of the Employee / Business Establishment": "Oracle",
                "Address": "A-705, Sec-12, Noida 201301",
                "Designation": "Developer",
                "Department": "IT",
                "Co-Borrower Full Name": "Arun Singh",
                "Co-Borrower Father's Name": "Ram Singh",
                "Co-Borrower Residence Address": "H.No-6, Janata Flats, Sec-31, Noida",
                "Co-Borrower Ph. No. (Res.)": "",
                "Co-Borrower Office": "",
                "Co-Borrower Family Mob. No.": "8649928580",
                "Co-Borrower Name of the Employee / Business Establishment": "Oracle",
                "Co-Borrower Address": "A-705, Sec-12, Noida 201301",
                "Co-Borrower Designation": "Developer",
                "Co-Borrower Department": "IT",
                "Guarantor 1 Name": "Sumit Kumar",
                "Guarantor 1 Address": "H-No-101, Noida, Sec-34 201301",
                "Guarantor 1 Ph. No. (Res.)": "8654796786",
                "Guarantor 2 Name": "Dilip Kumar",
                "Guarantor 2 Address": "H-No-46, Noida UU 201301",
                "Guarantor 2 Ph. No. (Res.)": "8722796234",
                "Reference 1 Name": "Amit Kumar",
                "Reference 1 Address": "H-46, Sec-46, Noida",
                "Reference 1 City": "",
                "Reference 1 Pin Code": "201301",
                "Reference 1 Ph. No. (Res.)": "8654798010",
                "Reference 2 Name": "Ranvir Singh",
                "Reference 2 Address": "H-44, Sec-44, Noida",
                "Reference 2 Ph. No. (Res.)": "8677986031",
                "Signature of the Borrower": "Anil Kumar",
                "Signature of the Co-Borrower": "Arun Singh",
                "Signature of the Guarantor": "Sumit Kumar",
                "REMARKS": ""
            }
        }
    ]
}
 